apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kibana-logging
  name: kibana-logging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - env:
        - name: SERVER_BASEPATH
          value: /kibana
        image: registry.mayadata.io/kibana:{{ .Values.server.release }}
        imagePullPolicy: Always
        name: kibana-logging
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 100m
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}

