apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kibana-logging
  name: kibana-logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    k8s-app: kibana-logging
  type: ClusterIP     

